apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightswebapp
spec:
  selector:
    matchLabels:
      app: flightswebapp
  replicas: 2
  template:
    metadata:
      labels:
        app: flightswebapp
    spec:
      containers:
      - name: flightswebapp
        image: docker.io/jptabja/flightswebapp:v1
        ports:
        - containerPort: 80