apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappoc
spec:
  selector:
    matchLabels:
      app: myappoc
  replicas: 2
  template:
    metadata:
      labels:
        app: myappoc
    spec:
      containers:
      - name: myappoc
        image: docker.io/jptabja/superbankassistant:latest
        ports:
        - containerPort: 8080