apiVersion: apps/v1
kind: Deployment
metadata:
 name: flightswebapp
 labels:
    app: flightswebapp
spec:
 replicas: 2
 selector:
    matchLabels:
      app: flightswebapp
 template:
    metadata:
       labels:
        app: flightswebapp
    spec:
      containers:
      - name: flightswebappcontainer
        image: docker.io/jptabja/flightswebapp:v1
        ports:
        - containerPort: 80