apiVersion: v1
kind: Service
metadata:
 name: flightswebapp
spec:
 type: NodePort
 selector:
   app: flightswebapp
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32089
selector:
  app: flightswebapp